//this is a test
try{
	SizerFlag = {
		"TOP": WGUI.SizerFlag.TOP,
		"BOTTOM": WGUI.SizerFlag.BOTTOM,
		"LEFT": WGUI.SizerFlag.LEFT,
		"RIGHT": WGUI.SizerFlag.RIGHT,
		"ALL": WGUI.SizerFlag.ALL,
		"EXPAND": WGUI.SizerFlag.EXPAND,
		"SHAPED": WGUI.SizerFlag.SHAPED,
		"FIXED_MINSIZE": WGUI.SizerFlag.FIXED_MINSIZE,
		"RESERVE_SPACE_EVEN_IF_HIDDEN": WGUI.SizerFlag.RESERVE_SPACE_EVEN_IF_HIDDEN,
		"ALIGN_CENTER": WGUI.SizerFlag.ALIGN_CENTER,
		"ALIGN_CENTER_VERTICAL": WGUI.SizerFlag.ALIGN_CENTER_VERTICAL,
		"ALIGN_CENTER_HORIZONTAL": WGUI.SizerFlag.ALIGN_CENTER_HORIZONTAL,
		"ALIGN_LEFT": WGUI.SizerFlag.ALIGN_LEFT,
		"ALIGN_RIGHT": WGUI.SizerFlag.ALIGN_RIGHT,
		"ALIGN_TOP": WGUI.SizerFlag.ALIGN_TOP,
		"ALIGN_BOTTOM": WGUI.SizerFlag.ALIGN_BOTTOM
	}
}
catch(e)
{
	alert("error:",e);
}